{%set conda_forge_name = "python-couchdb" %}
{%set name = "CouchDB" %}
{%set version = "1.2" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "1386a1a43f25bed3667e3b805222054940d674fa1967fa48e9d2012a18630ab7" %}

package:
  name: {{ conda_forge_name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  entry_points:
    - couchpy = couchdb.view:main
    - couchdb-dump = couchdb.tools.dump:main
    - couchdb-load = couchdb.tools.load:main
    - couchdb-replicate = couchdb.tools.replicate:main
    - couchdb-load-design-doc = couchdb.loader:main
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python

test:
  imports:
    - couchdb
    - couchdb.tests
    - couchdb.tools

  commands:
    - couchpy --help
    - couchdb-dump --help
    - couchdb-load --help
    - couchdb-replicate --help
    # couchdb-load-design-doc requires a design doc, so untested

about:
  home: https://github.com/djc/couchdb-python/
  license: BSD 3-Clause
  license_file: COPYING
  license_family: BSD
  summary: 'Python library for working with CouchDB'
  dev_url: https://github.com/djc/couchdb-python/
  doc_url: https://pythonhosted.org/CouchDB/

extra:
  recipe-maintainers:
    - pmlandwehr
