travis:
  secure:
    BINSTAR_TOKEN: lSMe6sr/l8QPAgFH/LMHeOZ3WGDqnBW+M0CU5Wpxy26KabpYZnLS70tcqWpm50zjQFVwqsVlbWrlWhWXLztE8ykUeTyVeYvafQDW5tcQLIEc+0v90fr24RavVXl8LpVkJ2P6VI5dyWJQfqWekVs3xrgXWeNvV6g+v/tMqrgyEaSL7PgynMINNG9TjvIFsYS/d1YQsv0MfRsdtMAua7hsfbfCvSFHEWq6S1D2iSn66ulh0Dyw5OQ/v7OQbvGNhIdik3IEhdCgjtWlX2o/aMHuDz91VznDW4vX3A6bqKmbfxI4DLTApuqISvAwRya/9XocYe3qiv18fjOUMRq2IEb3iVqsUKLzKMMymwdV5+3mxT+BIjCWDngzYxsTv6W4SuWf6f8g1dshnqQnx22k65YRb9pqxSRGRJpsBZdCtt0+qPJEj5kOR0ha5r/vIxZRm7bIOtu1DBR2r1QMaqfT19IucJvkEhPryB3kLTBAJg9I8bFmYO2+UVUk6KNy0S3NFI4Fyw+BySUP82mv613FEM+j1CQpng2PlptrKei7q0tW/qoiUqX9M0mv/lLemdivC+90pKxTLxl0kxbGRcuXzw59hjPNJHtgymHLBRFy/MIVoTCZtkSuBSEtq9a3kWq9DwOsUxfPRmKcqH5HAf4ZdkgCZ1BAblY7ToijOsHaQWeWTYw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
