travis:
  secure:
    BINSTAR_TOKEN: u+s3t87IC1Q5q6zFHs+xh3cq0GSh9fW6fUcNTdjnN4r1cHcEj61xxFl/d/WNLMmuQn6ZC3FSZNBJxPBN5vHAvR6aGT/T68PJxN5Xk7x8UUSWXOFKhL/7e72+ZF+KdrFfit6vGVJ8DkV8Bsi0HdOMLLIRtnY13LzdskgwrWYRZKEfy13sXWFuzfIlDCLQxpdeuT3AJ2aKx7NhEYjFQ/bT9uOG6HaoyAMizKjqpmv7krIen5rmYYU4g3KdRZ6UFptMH+CvS2HooRddKcqOSNcDHhhBc7O7wLBjlcypff1PtW1f88boSkA9aNoOu6yb9//xfzYxFc0FxevQkli98AYMgVCysETl80O9dWWNKwEzuYf6Y/FWEH31HSCC3Fu1UshYKPdF4a6/bvjKRamFDHzRPcnFwmdtjnsoUUphh+dC0OROicPvVFwN3uBpb5gfN/g0Ghx88aavzdiXysyQrBZjM5Mfqzf/mIkO9noEdqmagwC9sFmrCdAC9dflQbu34zzo3LWJ2RA77LwYr7uVxRuVeAu4x8ZkTVZTZSTNqZrz7qryYRmiOBKR66gOBl0omAcEJnMYtEFnq4gVGJzpfgey8zn1aWQFkObTwLs+LKHLHtS5TS6fXtAho0yDpksMpKsfoDXy0bFbqAgXWF037nd5NoD6WlPhPX+gKiCEQUsXBIM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
